### ISSUE TITLE
Callbacks for configuring sockets?

### ISSUE THREAD

**Issue by jephthai** [forthy42/gforth#13]
For the unix/socket.fs code, I had a project where I wanted to use the 'open-socket' code, but needed to set a socket option during socket creation.  I ended up modifying the socket.fs as follows:

```
diff foo/socket.fs socket.fs
354a355,357
> defer get-socket-options
> :noname ; is get-socket-options
> 
357a361
>             get-socket-options
```
This enabled me to add the following in my program:
```
6 constant IPPROTO_TCP
7 constant TCP_SYNCNT
create SYN_COUNT 1 , 

:noname dup IPPROTO_TCP TCP_SYNCNT SYN_COUNT 4 setsockopt ?ior ;
is get-socket-options
```
It seems like this sort of strategy might be helpful for others who want an abstract socket library, but may need to customize its operation.  Using some deferred words as callbacks makes this pretty easy, and (I think) elegant, without a significant penalty.  The alternative for me was to duplicate a bunch of the socket.fs code in my program, which defeats the purpose of having a library, IMO.

**Comment by forthy42** [comment]
Ok.  I added the code you asked for.  Next time, please send a unified diff, please. Or a pull request.
