### ISSUE TITLE
No error report on exception

### ISSUE THREAD

**Issue by ruv** [forthy42/gforth#15]
`ABORT` and `THROW` do not show any error report in case of the exception is not caught.

The code
```forth
:noname -1 throw 123 . ; execute
```
outputs
```
  ok
```

Gforth 0.7.9_20180905 on Debian 3.16

**Comment by forthy42** [comment]
Yes, that's how the Standard specifies what ```ABORT``` is supposed to do:

> Empty the data stack and perform the function of ```QUIT```, which includes emptying the return stack, _without displaying a message._

Same for -1 THROW:

> If n is minus-one (-1), perform the function of 6.1.0670 ```ABORT``` (the version of ```ABORT``` in the Core word set), displaying no message.

Agreed that this is somewhat weird, but that's how the standard specifies this.

**Comment by ruv** [comment]
Oh, I see. Thanks for clarification.  
It is also confusing since in the older versions (0.7.2 at least) an error was reported in these case.

**Comment by forthy42** [comment]
Yes, but this was a bug.
