### ISSUE TITLE
Strange "invalid memory address" error with [else]

### ISSUE THREAD

**Issue by ruv** [forthy42/gforth#16]
Gforth 0.7.9_20180905

The code:
```forth
: 0?E ( 0|x -- 0|x ) ]] dup 0= if exit then [[ ; immediate
: execute-name? ( i*x c-addr u -- j*x flag ) find-name 0?E name>interpret 0?E execute true ; 

S" [ELSE]" execute-name? [THEN]
.
```

The output:
```
*the terminal*:4: error: Invalid memory address
>>>.<<<
```

The same issue with the following code:
```forth
0 S" [IF]" execute-name? [THEN]
.
```

**Comment by forthy42** [comment]
[ELSE] pushes the current parser hook onto the stack, and replaces it with a parser hook that looks for [THEN] (and similar words). [THEN] pops that hook from the stack.

Since your execute-name? returns true, that true is consumed by [THEN], as parser hook. Of course, calling that hook then will fail.

**Comment by ruv** [comment]
I see.  And is it a bug or not?  Either my code or Gforth code does not conform to the standard, or another case also exists. (?)

Obviously, the general solution is to use the separate control flow stack.

**[UPD]**
By the [standard](https://forth-standard.org/standard/tools/BracketELSE), `[IF]` and `[ELSE]` shall be the parsing words. It means that when `[ELSE]` has executed, the parse area should contain the fragment after the corresponding `[THEN]`. In Gforth it is not held.

So, the separate control flow stack will not solve this nonconformance.  In the approach when the current parser hook is changed, — the nesting call of the outer interpreter loop is needed.

**Comment by forthy42** [comment]
Yes, that sounds reasonable, so I change Gforth's behavior to scan actively.

**Comment by ruv** [comment]
Just a reference to the corresponding commit: 5b787240
