### ISSUE TITLE
chcon: failed to get security context of 'libgforth-ditc': Operation not supported

### ISSUE THREAD

**Issue by odiferousmint** [forthy42/gforth#28]
I ran `./BUILD-FROM-SCRATCH` which basically just does: `./autogen.sh && ./configure && make`.
It fails with:

```
make[1]: Leaving directory '/tmp/gforth-0.7.9_20201022/engine'
ln -s -f engine/libgforth-ditc libgforth-ditc
chcon -t unconfined_execmem_exec_t libgforth-ditc || true
chcon: failed to get security context of 'libgforth-ditc': Operation not supported
```

Workaround is modifying the `Makefile` and changing the line with `chcon` to `true`, for example.

**Comment by forthy42** [comment]
Am Sonntag, 25. Oktober 2020, 01:44:15 CET schrieb odiferousmint:
> I ran `./BUILD-FROM-SCRATCH` which basically just does: `./autogen.sh &&
> ./configure && make`. It fails with:
> 
> ```
> make[1]: Leaving directory '/tmp/gforth-0.7.9_20201022/engine'
> ln -s -f engine/libgforth-ditc libgforth-ditc
> chcon -t unconfined_execmem_exec_t libgforth-ditc || true
> chcon: failed to get security context of 'libgforth-ditc': Operation not
> supported ```

No, it does not fail. It reports that chcon is not supported.  SELinux 
requires this chcon, and to make sure it does not fail, it's || true in the 
rule.

-- 
Bernd Paysan
"If you want it done right, you have to do it yourself"
net2o id: kQusJzA;7*?t=uy@X}1GWr!+0qqp_Cn176t4(dQ*
https://net2o.de/

**Comment by odiferousmint** [comment]
I see. In that case, it should be closed.
