### ISSUE TITLE
Issue with calling C functions: "called function of unfinished named C library"

### ISSUE THREAD

**Issue by odiferousmint** [forthy42/gforth#29]
Example code:

```forth
C-LIBRARY <stdlib.h>
c-function stdlib_abs abs n -- n
-3 stdlib_abs .
```

Output:

```
-3 stdlib_abs . 
*the terminal*:11:4: error: Called function of unfinished named C library
-3 >>>stdlib_abs<<< .
Backtrace:
libcc.fs:1027:20:                        0 $7F9979D98E30 throw 
libcc.fs:918:2:                          1 $7F9979D98138 compile-wrapper-function 
libcc.fs:932:12:                         2 $7F9979D98340 ?compile-wrapper
```

Any ideas as to why? This code works with the old gforth 0.7.3, apart from `C-LIBRARY <stdlib.h>` being `\c #include <stdlib.h>` instead.

**Comment by forthy42** [comment]
Am Sonntag, 25. Oktober 2020, 02:00:15 CET schrieb odiferousmint:
> Example code:
> 
> ```forth
> C-LIBRARY <stdlib.h>
> c-function stdlib_abs abs n -- n
> -3 stdlib_abs .
> ```
> 
> Output:
> 
> ```
> -3 stdlib_abs .
> *the terminal*:11:4: error: Called function of unfinished named C library
> -3 >>>stdlib_abs<<< .
> Backtrace:
> libcc.fs:1027:20:                        0 $7F9979D98E30 throw
> libcc.fs:918:2:                          1 $7F9979D98138
> compile-wrapper-function libcc.fs:932:12:                         2
> $7F9979D98340 ?compile-wrapper ```
> 
> Any ideas as to why? This code works with the old gforth 0.7.3, apart from
> `C-LIBRARY <stdlib.h>` being `\c #include <stdlib.h>` instead.

See the manual. You need to define a named c-library, and end it; it's only 
compiled after ending.  The 0.7.3 mechanism to compile on the fly was not a 
good idea.

c-library stdlib
\c #include <stdlib.h>
c-function stdlib_abs abs n -- n
end-c-library

https://gforth.org/manual/Defining-library-interfaces.html

-- 
Bernd Paysan
"If you want it done right, you have to do it yourself"
net2o id: kQusJzA;7*?t=uy@X}1GWr!+0qqp_Cn176t4(dQ*
https://net2o.de/

**Comment by odiferousmint** [comment]
Alrighties, thank you for the help!
