### ISSUE TITLE
Inappropriate error message in um/mod

### ISSUE THREAD

**Issue by ruv** [forthy42/gforth#32]
Gforth 0.7.9_20210218, `gforth-fast` binary (and `gforth-fast-ll-reg`):

```
-1 -1  1  um/mod . .
```

The actual error message: "Division by zero"

An expected error message: "Integer overflow"

Initially, the [question appeared](https://stackoverflow.com/q/66976303/1300170) on the StackOverflow.

NB: `gforth`, `gforth-itc`, `gforth-ditc`, `gforth-ll-reg` binaries show in this test an error message: "Result out of range".

**Comment by ruv** [comment]
Testing the version `0.7.9_20211028 amd64` shows that this issue still exists. Update: only `gforth-fast` and `gforth-fast-ll-reg` binaries show this issue, other binaries doesn't (it's the same as in the version 0.7.9_20210218).

**Comment by forthy42** [comment]
Yes, the -fast engine does make some compromises speed vs. accuracy of error messages.  This is intentional, the correct error message requires extra code that is slowing down division a bit.

**Comment by ruv** [comment]
Then it's by design. I see. Probably is should be documented in [Error messages](https://gforth.org/manual/Error-messages.html).
