### ISSUE TITLE
Files with two dots do not work under Windows!

### ISSUE THREAD

**Issue by mofrisch** [forthy42/gforth#35]
There are some files which include two dots. Therefore, a git clone to Windows does not work.

**Comment by forthy42** [comment]
Works with Cygwin's git. And since Gforth only builds with Cygwin (on Windows), I don't see a problem.

**Comment by mofrisch** [comment]
OK. I didn't know that. Meanwhile I used it in WSL and it works fine there too. I'm a Windows newbie. Thank you very much.

**Comment by forthy42** [comment]
WSL is a good choice, too.

**Comment by mofrisch** [comment]
Works like a charm now.
