### ISSUE TITLE
clang build hangs NetBSD 8.99.1 - clang 5.0svn

### ISSUE THREAD

**Issue by krytarowski** [forthy42/gforth#6]
NetBSD chieftec 8.99.1 NetBSD 8.99.1 (GENERIC) #1: Thu Jun 22 19:26:57 CEST 2017  root@chieftec:/public/netbsd-root/sys/arch/amd64/compile/GENERIC amd64

gforth 0.7.3 in pkgsrc

clang 5.0.0 (from llvm-svn trunk version)

Build hangs on this command:

>>> clang -I./../arch/amd64 -I. -Wall -O2 -Dunix -Og -g -ggdb -I/usr/pkg/include -I/usr/include -DHAVE_CONFIG_H -DFORCE_LL -DFORCE_REG -DDEFAULTPATH=".:/usr/pkg/lib/gforth/site-forth:/usr/pkg/share/gforth/site-forth:/usr/pkg/lib/gforth/0.7.3:/usr/pkg/share/gforth/0.7.3" -I/usr/pkg/include -I/usr/include -fno-gcse -fno-strict-aliasing -fno-reorder-blocks -falign-labels=1 -falign-loops=1 -falign-jumps=1 -DGFORTH_DEBUGGING -o engine-ll-reg.o -c ./engine.c

**Comment by forthy42** [comment]
Am Samstag, 24. Juni 2017, 01:43:43 CEST schrieb Kamil Rytarowski:
> NetBSD chieftec 8.99.1 NetBSD 8.99.1 (GENERIC) #1: Thu Jun 22 19:26:57 CEST
> 2017  root@chieftec:/public/netbsd-root/sys/arch/amd64/compile/GENERIC
> amd64
> 
> gforth 0.7.3 in pkgsrc
> 
> clang 5.0.0 (from llvm-svn trunk version)
> 
> Build hangs on this command:
> >>> clang -I./../arch/amd64 -I. -Wall -O2 -Dunix -Og -g -ggdb
> >>> -I/usr/pkg/include -I/usr/include -DHAVE_CONFIG_H -DFORCE_LL
> >>> -DFORCE_REG
> >>> -DDEFAULTPATH=".:/usr/pkg/lib/gforth/site-forth:/usr/pkg/share/gforth/s
> >>> ite-forth:/usr/pkg/lib/gforth/0.7.3:/usr/pkg/share/gforth/0.7.3"
> >>> -I/usr/pkg/include -I/usr/include -fno-gcse -fno-strict-aliasing
> >>> -fno-reorder-blocks -falign-labels=1 -falign-loops=1 -falign-jumps=1
> >>> -DGFORTH_DEBUGGING -o engine-ll-reg.o -c ./engine.c

It doesn't completely hang, clang is just incredibly slow to compile Gforth.  
That is a known clang/llvm bug.

https://bugs.llvm.org//show_bug.cgi?id=22609

If you can't wait for clang to fix their bug (register coalescing of this big 
computed goto engine is apparently O(n^2) or even O(n^3)), compile with GCC 
instead.

-- 
Bernd Paysan
"If you want it done right, you have to do it yourself"
net2o ID: kQusJzA;7*?t=uy@X}1GWr!+0qqp_Cn176t4(dQ*
http://bernd-paysan.de/
