### ISSUE TITLE
Needed to install `libltdl-dev` on Ubuntu when building from source

### ISSUE THREAD

**Issue by RickCarlino** [forthy42/gforth#7]
# Problem

I attempted to build from source using the instructions in `install.md`.

When doing so, I hit the following error:

```
libtoolize: error: '/usr/share/aclocal/ltdl.m4' does not exist.
```

# Solution

I was able to solve the problem by simply running

```
sudo apt-get install libltdl-dev
```

My question is: was this a configuration error on my part? If it is actually a required dependency for installation, I would be more than happy to update `install.md` and submit a pull request.

**Comment by forthy42** [comment]
Yes, for building, it should be libltdl-dev.
